r"""Critical-value tables and the synthetic example dataset shipped with the package.

Attributes
----------
F_CRITICAL_VALUES_POWER_RHO : `str`
    Location of a CSV file containing critical values for power for each combination of :math:`\rho` and number of
    instruments.
F_CRITICAL_VALUES_SIZE_RHO : `str`
    Location of a CSV file containing critical values for size for each combination of :math:`\rho` and number of
    instruments.
EXAMPLE_SYNTHETIC : `str`
    Location of a small synthetic dataset (T=3000 markets, J=2 single-product firms) generated under
    perfect-competition pricing with logit demand. Used by the README quick-start.

Examples
--------
>>> from pyRVtest import data
>>> data.F_CRITICAL_VALUES_POWER_RHO.endswith('.csv')
True
>>> data.F_CRITICAL_VALUES_SIZE_RHO.endswith('.csv')
True
>>> power, size = data.read_critical_values_tables()
>>> power.dtype.names
('K', 'rho', 'r_50', 'r_75', 'r_95')
>>> size.dtype.names
('K', 'rho', 'r_075', 'r_10', 'r_125')
"""

from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

if TYPE_CHECKING:
    import pandas as pd


_DATA_PATH = Path(__file__).resolve().parent
F_CRITICAL_VALUES_POWER_RHO = str(_DATA_PATH / 'f_critical_values_power_rho.csv')
F_CRITICAL_VALUES_SIZE_RHO = str(_DATA_PATH / 'f_critical_values_size_rho.csv')
EXAMPLE_SYNTHETIC = str(_DATA_PATH / 'example_synthetic.csv')

_critical_values_cache: Optional[Tuple[NDArray[Any], NDArray[Any]]] = None


def read_critical_values_tables() -> Tuple[NDArray[Any], NDArray[Any]]:
    """Read in the critical values for size and power from the corresponding csv file. These will be used to evaluate
    the strength of the instruments. Results are cached after the first read.

    Examples
    --------
    >>> from pyRVtest.data import read_critical_values_tables
    >>> power, size = read_critical_values_tables()
    >>> power.shape[0] > 0
    True
    >>> size.shape[0] > 0
    True
    """
    global _critical_values_cache
    if _critical_values_cache is not None:
        return _critical_values_cache

    # read in data for critical values for size as a structured array
    critical_values_size = np.genfromtxt(
        F_CRITICAL_VALUES_SIZE_RHO,
        delimiter=',',
        skip_header=1,
        dtype=[('K', 'i4'), ('rho', 'f8'), ('r_075', 'f8'), ('r_10', 'f8'), ('r_125', 'f8')]
    )

    # read in data for critical values for power as a structured array
    critical_values_power = np.genfromtxt(
        F_CRITICAL_VALUES_POWER_RHO,
        delimiter=',',
        skip_header=1,
        dtype=[('K', 'i4'), ('rho', 'f8'), ('r_50', 'f8'), ('r_75', 'f8'), ('r_95', 'f8')]
    )

    _critical_values_cache = (critical_values_power, critical_values_size)
    return _critical_values_cache


def load_example() -> 'pd.DataFrame':
    """Load the synthetic example dataset used in the README quick-start.

    Equivalent to :func:`simulate_example` at default arguments — the
    shipped CSV is generated by that function with ``T=3000, seed=42``.
    See :func:`simulate_example` for the data-generating process.

    Columns:

    - ``market_ids``, ``firm_ids``: market and firm identifiers.
    - ``shares``, ``prices``: equilibrium product shares and prices.
    - ``x1``: an exogenous demand-side product characteristic.
    - ``z1``, ``z2``: exogenous own cost shifters.
    - ``rival_z1``, ``rival_z2``: rival cost shifters (sum of rivals'
      values within each market). Used as testing instruments per
      Dearing et al. (2026).

    Returns
    -------
    pandas.DataFrame
        The simulated dataset, ready to pass into :class:`pyRVtest.Problem`.
    """
    import pandas as pd
    return pd.read_csv(EXAMPLE_SYNTHETIC)


def simulate_example(T: int = 3000, seed: int = 42) -> 'pd.DataFrame':
    r"""Generate the synthetic example dataset programmatically.

    The defaults reproduce the dataset shipped via :func:`load_example`.
    Exposed so users can inspect the data-generating process, vary the
    seed or sample size, and verify the demo is not cherry-picked.

    Data-generating process
    -----------------------
    Two single-product firms (:math:`F=2,\, K=1`) compete in :math:`T`
    independent markets under **perfect competition** (the truth in the
    shipped dataset).

    Marginal cost (per-product, market):

    .. math::

        mc_{jt} = \max(\gamma_0 + \gamma_1 z_{1,jt} + \gamma_2 z_{2,jt}
                       + \omega_{jt},\ 0.1)

    with :math:`\gamma_0 = 2,\ \gamma_1 = 2,\ \gamma_2 = 1,\
    \omega_{jt} \sim \mathcal{N}(0, 0.5)`. Prices are set at marginal
    cost: :math:`p_{jt} = mc_{jt}`.

    Demand is plain logit:

    .. math::

        \delta_{jt} = \beta_0 + \alpha p_{jt} + \beta_1 x_{1,jt}
                     + \xi_{jt},\quad
        s_{jt} = \frac{\exp(\delta_{jt})}
                      {1 + \sum_{k} \exp(\delta_{kt})}

    with :math:`\beta_0 = 2,\ \alpha = -1,\ \beta_1 = 1,\
    \xi_{jt} \sim \mathcal{N}(0, 0.3)`. ``x1``, ``z1``, ``z2`` are iid
    standard normal across observations. ``rival_z1`` (resp. ``rival_z2``)
    is the sum of rivals' ``z1`` (resp. ``z2``) within each market.

    Parameters
    ----------
    T : int, default 3000
        Number of markets.
    seed : int, default 42
        Random seed.

    Returns
    -------
    pandas.DataFrame
        Identical schema to :func:`load_example`.
    """
    import pandas as pd

    F, K = 2, 1
    J = F * K
    N = T * J
    rng = np.random.default_rng(seed)

    market_ids = np.repeat(np.arange(T), J)
    firm_ids = np.tile(np.repeat(np.arange(F), K), T)

    x1 = rng.standard_normal(N)
    z1 = rng.standard_normal(N)
    z2 = rng.standard_normal(N)
    xi = rng.standard_normal(N) * np.sqrt(0.3)
    omega = rng.standard_normal(N) * np.sqrt(0.5)

    mc = np.maximum(2.0 + 2.0 * z1 + 1.0 * z2 + omega, 0.1)
    prices = mc  # perfect competition: prices equal marginal cost

    delta = 2.0 + (-1.0) * prices + 1.0 * x1 + xi
    shares = np.empty(N)
    for t in range(T):
        idx = np.where(market_ids == t)[0]
        ed = np.exp(delta[idx])
        shares[idx] = ed / (1 + ed.sum())

    rival_z1 = np.empty(N)
    rival_z2 = np.empty(N)
    for t in range(T):
        idx = np.where(market_ids == t)[0]
        for j in idx:
            rivals = [i for i in idx if i != j]
            rival_z1[j] = z1[rivals].sum()
            rival_z2[j] = z2[rivals].sum()

    return pd.DataFrame({
        'market_ids': market_ids,
        'firm_ids': firm_ids,
        'shares': shares,
        'prices': prices,
        'x1': x1,
        'z1': z1,
        'z2': z2,
        'rival_z1': rival_z1,
        'rival_z2': rival_z2,
    })
